<!DOCTYPE html>
<html>
   <head>
      <title>env\Lib\site-packages\trio\_core\_exceptions.py - flake8 annotated source</title>
      <meta http-equiv="Content-Type" value="text/html; charset=UTF-8">
      <link rel="stylesheet" href="styles.css">
   </head>
   <body>
      <div id="masthead" class="sev-1"></div>
      <div id="page">
         <h1>
            <a href="env.Lib.site-packages.trio._core._exceptions.report.html">
               <img src="back.svg" alt="&#x2B05;">
               env\Lib\site-packages\trio\_core\_exceptions.py source
            </a>
         </h1>

         <div id="doc">
            <div id="l1"
               class="code sev-1  le">
               <ul class="violations">
               
                  <li>
                     <span class="count sev-1">
                        F401
                     </span>
                     'attr' imported but unused</li>
               
               </ul><tt><i>1</i> <span class="kn">import</span> <span class="nn">attr</span></tt>
            </div>
            <div id="l2"
               class="code sev- "><tt><i>2</i> &nbsp;</tt>
            </div>
            <div id="l3"
               class="code sev- "><tt><i>3</i> <span class="kn">from</span> <span class="nn">trio._util</span> <span class="kn">import</span> <span class="n">NoPublicConstructor</span></tt>
            </div>
            <div id="l4"
               class="code sev- "><tt><i>4</i> &nbsp;</tt>
            </div>
            <div id="l5"
               class="code sev- "><tt><i>5</i> &nbsp;</tt>
            </div>
            <div id="l6"
               class="code sev- "><tt><i>6</i> <span class="k">class</span> <span class="nc">TrioInternalError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span></tt>
            </div>
            <div id="l7"
               class="code sev- "><tt><i>7</i>     <span class="sd">&quot;&quot;&quot;Raised by :func:`run` if we encounter a bug in Trio, or (possibly) a</span></tt>
            </div>
            <div id="l8"
               class="code sev- "><tt><i>8</i> <span class="sd">    misuse of one of the low-level :mod:`trio.lowlevel` APIs.</span></tt>
            </div>
            <div id="l9"
               class="code sev- "><tt><i>9</i> &nbsp;</tt>
            </div>
            <div id="l10"
               class="code sev- "><tt><i>10</i> <span class="sd">    This should never happen! If you get this error, please file a bug.</span></tt>
            </div>
            <div id="l11"
               class="code sev- "><tt><i>11</i> &nbsp;</tt>
            </div>
            <div id="l12"
               class="code sev- "><tt><i>12</i> <span class="sd">    Unfortunately, if you get this error it also means that all bets are off â€“</span></tt>
            </div>
            <div id="l13"
               class="code sev- "><tt><i>13</i> <span class="sd">    Trio doesn&#39;t know what is going on and its normal invariants may be void.</span></tt>
            </div>
            <div id="l14"
               class="code sev- "><tt><i>14</i> <span class="sd">    (For example, we might have &quot;lost track&quot; of a task. Or lost track of all</span></tt>
            </div>
            <div id="l15"
               class="code sev- "><tt><i>15</i> <span class="sd">    tasks.) Again, though, this shouldn&#39;t happen.</span></tt>
            </div>
            <div id="l16"
               class="code sev- "><tt><i>16</i> &nbsp;</tt>
            </div>
            <div id="l17"
               class="code sev- "><tt><i>17</i> <span class="sd">    &quot;&quot;&quot;</span></tt>
            </div>
            <div id="l18"
               class="code sev- "><tt><i>18</i> &nbsp;</tt>
            </div>
            <div id="l19"
               class="code sev- "><tt><i>19</i> &nbsp;</tt>
            </div>
            <div id="l20"
               class="code sev- "><tt><i>20</i> <span class="k">class</span> <span class="nc">RunFinishedError</span><span class="p">(</span><span class="ne">RuntimeError</span><span class="p">):</span></tt>
            </div>
            <div id="l21"
               class="code sev- "><tt><i>21</i>     <span class="sd">&quot;&quot;&quot;Raised by `trio.from_thread.run` and similar functions if the</span></tt>
            </div>
            <div id="l22"
               class="code sev- "><tt><i>22</i> <span class="sd">    corresponding call to :func:`trio.run` has already finished.</span></tt>
            </div>
            <div id="l23"
               class="code sev- "><tt><i>23</i> &nbsp;</tt>
            </div>
            <div id="l24"
               class="code sev- "><tt><i>24</i> <span class="sd">    &quot;&quot;&quot;</span></tt>
            </div>
            <div id="l25"
               class="code sev- "><tt><i>25</i> &nbsp;</tt>
            </div>
            <div id="l26"
               class="code sev- "><tt><i>26</i> &nbsp;</tt>
            </div>
            <div id="l27"
               class="code sev- "><tt><i>27</i> <span class="k">class</span> <span class="nc">WouldBlock</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span></tt>
            </div>
            <div id="l28"
               class="code sev- "><tt><i>28</i>     <span class="sd">&quot;&quot;&quot;Raised by ``X_nowait`` functions if ``X`` would block.&quot;&quot;&quot;</span></tt>
            </div>
            <div id="l29"
               class="code sev- "><tt><i>29</i> &nbsp;</tt>
            </div>
            <div id="l30"
               class="code sev- "><tt><i>30</i> &nbsp;</tt>
            </div>
            <div id="l31"
               class="code sev- "><tt><i>31</i> <span class="k">class</span> <span class="nc">Cancelled</span><span class="p">(</span><span class="ne">BaseException</span><span class="p">,</span> <span class="n">metaclass</span><span class="o">=</span><span class="n">NoPublicConstructor</span><span class="p">):</span></tt>
            </div>
            <div id="l32"
               class="code sev- "><tt><i>32</i>     <span class="sd">&quot;&quot;&quot;Raised by blocking calls if the surrounding scope has been cancelled.</span></tt>
            </div>
            <div id="l33"
               class="code sev- "><tt><i>33</i> &nbsp;</tt>
            </div>
            <div id="l34"
               class="code sev- "><tt><i>34</i> <span class="sd">    You should let this exception propagate, to be caught by the relevant</span></tt>
            </div>
            <div id="l35"
               class="code sev- "><tt><i>35</i> <span class="sd">    cancel scope. To remind you of this, it inherits from :exc:`BaseException`</span></tt>
            </div>
            <div id="l36"
               class="code sev- "><tt><i>36</i> <span class="sd">    instead of :exc:`Exception`, just like :exc:`KeyboardInterrupt` and</span></tt>
            </div>
            <div id="l37"
               class="code sev- "><tt><i>37</i> <span class="sd">    :exc:`SystemExit` do. This means that if you write something like::</span></tt>
            </div>
            <div id="l38"
               class="code sev- "><tt><i>38</i> &nbsp;</tt>
            </div>
            <div id="l39"
               class="code sev- "><tt><i>39</i> <span class="sd">       try:</span></tt>
            </div>
            <div id="l40"
               class="code sev- "><tt><i>40</i> <span class="sd">           ...</span></tt>
            </div>
            <div id="l41"
               class="code sev- "><tt><i>41</i> <span class="sd">       except Exception:</span></tt>
            </div>
            <div id="l42"
               class="code sev- "><tt><i>42</i> <span class="sd">           ...</span></tt>
            </div>
            <div id="l43"
               class="code sev- "><tt><i>43</i> &nbsp;</tt>
            </div>
            <div id="l44"
               class="code sev- "><tt><i>44</i> <span class="sd">    then this *won&#39;t* catch a :exc:`Cancelled` exception.</span></tt>
            </div>
            <div id="l45"
               class="code sev- "><tt><i>45</i> &nbsp;</tt>
            </div>
            <div id="l46"
               class="code sev- "><tt><i>46</i> <span class="sd">    You cannot raise :exc:`Cancelled` yourself. Attempting to do so</span></tt>
            </div>
            <div id="l47"
               class="code sev- "><tt><i>47</i> <span class="sd">    will produce a :exc:`TypeError`. Use :meth:`cancel_scope.cancel()</span></tt>
            </div>
            <div id="l48"
               class="code sev- "><tt><i>48</i> <span class="sd">    &lt;trio.CancelScope.cancel&gt;` instead.</span></tt>
            </div>
            <div id="l49"
               class="code sev- "><tt><i>49</i> &nbsp;</tt>
            </div>
            <div id="l50"
               class="code sev- "><tt><i>50</i> <span class="sd">    .. note::</span></tt>
            </div>
            <div id="l51"
               class="code sev- "><tt><i>51</i> &nbsp;</tt>
            </div>
            <div id="l52"
               class="code sev- "><tt><i>52</i> <span class="sd">       In the US it&#39;s also common to see this word spelled &quot;canceled&quot;, with</span></tt>
            </div>
            <div id="l53"
               class="code sev- "><tt><i>53</i> <span class="sd">       only one &quot;l&quot;. This is a `recent</span></tt>
            </div>
            <div id="l54"
               class="code sev- "><tt><i>54</i> <span class="sd">       &lt;https://books.google.com/ngrams/graph?content=canceled%2Ccancelled&amp;year_start=1800&amp;year_end=2000&amp;corpus=5&amp;smoothing=3&amp;direct_url=t1%3B%2Ccanceled%3B%2Cc0%3B.t1%3B%2Ccancelled%3B%2Cc0&gt;`__</span></tt>
            </div>
            <div id="l55"
               class="code sev- "><tt><i>55</i> <span class="sd">       and `US-specific</span></tt>
            </div>
            <div id="l56"
               class="code sev- "><tt><i>56</i> <span class="sd">       &lt;https://books.google.com/ngrams/graph?content=canceled%2Ccancelled&amp;year_start=1800&amp;year_end=2000&amp;corpus=18&amp;smoothing=3&amp;share=&amp;direct_url=t1%3B%2Ccanceled%3B%2Cc0%3B.t1%3B%2Ccancelled%3B%2Cc0&gt;`__</span></tt>
            </div>
            <div id="l57"
               class="code sev- "><tt><i>57</i> <span class="sd">       innovation, and even in the US both forms are still commonly used. So</span></tt>
            </div>
            <div id="l58"
               class="code sev- "><tt><i>58</i> <span class="sd">       for consistency with the rest of the world and with &quot;cancellation&quot;</span></tt>
            </div>
            <div id="l59"
               class="code sev- "><tt><i>59</i> <span class="sd">       (which always has two &quot;l&quot;s), Trio uses the two &quot;l&quot; spelling</span></tt>
            </div>
            <div id="l60"
               class="code sev- "><tt><i>60</i> <span class="sd">       everywhere.</span></tt>
            </div>
            <div id="l61"
               class="code sev- "><tt><i>61</i> &nbsp;</tt>
            </div>
            <div id="l62"
               class="code sev- "><tt><i>62</i> <span class="sd">    &quot;&quot;&quot;</span></tt>
            </div>
            <div id="l63"
               class="code sev- "><tt><i>63</i> &nbsp;</tt>
            </div>
            <div id="l64"
               class="code sev- "><tt><i>64</i>     <span class="k">def</span> <span class="fm">__str__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span></tt>
            </div>
            <div id="l65"
               class="code sev- "><tt><i>65</i>         <span class="k">return</span> <span class="s2">&quot;Cancelled&quot;</span></tt>
            </div>
            <div id="l66"
               class="code sev- "><tt><i>66</i> &nbsp;</tt>
            </div>
            <div id="l67"
               class="code sev- "><tt><i>67</i> &nbsp;</tt>
            </div>
            <div id="l68"
               class="code sev- "><tt><i>68</i> <span class="k">class</span> <span class="nc">BusyResourceError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span></tt>
            </div>
            <div id="l69"
               class="code sev- "><tt><i>69</i>     <span class="sd">&quot;&quot;&quot;Raised when a task attempts to use a resource that some other task is</span></tt>
            </div>
            <div id="l70"
               class="code sev- "><tt><i>70</i> <span class="sd">    already using, and this would lead to bugs and nonsense.</span></tt>
            </div>
            <div id="l71"
               class="code sev- "><tt><i>71</i> &nbsp;</tt>
            </div>
            <div id="l72"
               class="code sev- "><tt><i>72</i> <span class="sd">    For example, if two tasks try to send data through the same socket at the</span></tt>
            </div>
            <div id="l73"
               class="code sev- "><tt><i>73</i> <span class="sd">    same time, Trio will raise :class:`BusyResourceError` instead of letting</span></tt>
            </div>
            <div id="l74"
               class="code sev- "><tt><i>74</i> <span class="sd">    the data get scrambled.</span></tt>
            </div>
            <div id="l75"
               class="code sev- "><tt><i>75</i> &nbsp;</tt>
            </div>
            <div id="l76"
               class="code sev- "><tt><i>76</i> <span class="sd">    &quot;&quot;&quot;</span></tt>
            </div>
            <div id="l77"
               class="code sev- "><tt><i>77</i> &nbsp;</tt>
            </div>
            <div id="l78"
               class="code sev- "><tt><i>78</i> &nbsp;</tt>
            </div>
            <div id="l79"
               class="code sev- "><tt><i>79</i> <span class="k">class</span> <span class="nc">ClosedResourceError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span></tt>
            </div>
            <div id="l80"
               class="code sev- "><tt><i>80</i>     <span class="sd">&quot;&quot;&quot;Raised when attempting to use a resource after it has been closed.</span></tt>
            </div>
            <div id="l81"
               class="code sev- "><tt><i>81</i> &nbsp;</tt>
            </div>
            <div id="l82"
               class="code sev- "><tt><i>82</i> <span class="sd">    Note that &quot;closed&quot; here means that *your* code closed the resource,</span></tt>
            </div>
            <div id="l83"
               class="code sev- "><tt><i>83</i> <span class="sd">    generally by calling a method with a name like ``close`` or ``aclose``, or</span></tt>
            </div>
            <div id="l84"
               class="code sev- "><tt><i>84</i> <span class="sd">    by exiting a context manager. If a problem arises elsewhere â€“ for example,</span></tt>
            </div>
            <div id="l85"
               class="code sev- "><tt><i>85</i> <span class="sd">    because of a network failure, or because a remote peer closed their end of</span></tt>
            </div>
            <div id="l86"
               class="code sev- "><tt><i>86</i> <span class="sd">    a connection â€“ then that should be indicated by a different exception</span></tt>
            </div>
            <div id="l87"
               class="code sev- "><tt><i>87</i> <span class="sd">    class, like :exc:`BrokenResourceError` or an :exc:`OSError` subclass.</span></tt>
            </div>
            <div id="l88"
               class="code sev- "><tt><i>88</i> &nbsp;</tt>
            </div>
            <div id="l89"
               class="code sev- "><tt><i>89</i> <span class="sd">    &quot;&quot;&quot;</span></tt>
            </div>
            <div id="l90"
               class="code sev- "><tt><i>90</i> &nbsp;</tt>
            </div>
            <div id="l91"
               class="code sev- "><tt><i>91</i> &nbsp;</tt>
            </div>
            <div id="l92"
               class="code sev- "><tt><i>92</i> <span class="k">class</span> <span class="nc">BrokenResourceError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span></tt>
            </div>
            <div id="l93"
               class="code sev- "><tt><i>93</i>     <span class="sd">&quot;&quot;&quot;Raised when an attempt to use a resource fails due to external</span></tt>
            </div>
            <div id="l94"
               class="code sev- "><tt><i>94</i> <span class="sd">    circumstances.</span></tt>
            </div>
            <div id="l95"
               class="code sev- "><tt><i>95</i> &nbsp;</tt>
            </div>
            <div id="l96"
               class="code sev- "><tt><i>96</i> <span class="sd">    For example, you might get this if you try to send data on a stream where</span></tt>
            </div>
            <div id="l97"
               class="code sev- "><tt><i>97</i> <span class="sd">    the remote side has already closed the connection.</span></tt>
            </div>
            <div id="l98"
               class="code sev- "><tt><i>98</i> &nbsp;</tt>
            </div>
            <div id="l99"
               class="code sev- "><tt><i>99</i> <span class="sd">    You *don&#39;t* get this error if *you* closed the resource â€“ in that case you</span></tt>
            </div>
            <div id="l100"
               class="code sev- "><tt><i>100</i> <span class="sd">    get :class:`ClosedResourceError`.</span></tt>
            </div>
            <div id="l101"
               class="code sev- "><tt><i>101</i> &nbsp;</tt>
            </div>
            <div id="l102"
               class="code sev- "><tt><i>102</i> <span class="sd">    This exception&#39;s ``__cause__`` attribute will often contain more</span></tt>
            </div>
            <div id="l103"
               class="code sev- "><tt><i>103</i> <span class="sd">    information about the underlying error.</span></tt>
            </div>
            <div id="l104"
               class="code sev- "><tt><i>104</i> &nbsp;</tt>
            </div>
            <div id="l105"
               class="code sev- "><tt><i>105</i> <span class="sd">    &quot;&quot;&quot;</span></tt>
            </div>
            <div id="l106"
               class="code sev- "><tt><i>106</i> &nbsp;</tt>
            </div>
            <div id="l107"
               class="code sev- "><tt><i>107</i> &nbsp;</tt>
            </div>
            <div id="l108"
               class="code sev- "><tt><i>108</i> <span class="k">class</span> <span class="nc">EndOfChannel</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span></tt>
            </div>
            <div id="l109"
               class="code sev- "><tt><i>109</i>     <span class="sd">&quot;&quot;&quot;Raised when trying to receive from a :class:`trio.abc.ReceiveChannel`</span></tt>
            </div>
            <div id="l110"
               class="code sev- "><tt><i>110</i> <span class="sd">    that has no more data to receive.</span></tt>
            </div>
            <div id="l111"
               class="code sev- "><tt><i>111</i> &nbsp;</tt>
            </div>
            <div id="l112"
               class="code sev- "><tt><i>112</i> <span class="sd">    This is analogous to an &quot;end-of-file&quot; condition, but for channels.</span></tt>
            </div>
            <div id="l113"
               class="code sev- "><tt><i>113</i> &nbsp;</tt>
            </div>
            <div id="l114"
               class="code sev- "><tt><i>114</i> <span class="sd">    &quot;&quot;&quot;</span></tt>
            </div>
            
         </div>
      </div>
   </body>
</html>